[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["app"]
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true
multi_line_output = 3

[tool.ruff]
target-version = "py311"
line-length = 88
select = ["F", "I", "TID"]  # F = Pyflakes, I = isort, TID = tidy imports
fix = true

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401"]  # Allow exports
